name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15]
        os: [macos-10.15]
        postgres-version: [13, 12, 11, 10, 9.6]
    steps:
    - uses: ankane/setup-postgres@v1
      with:
        postgres-version: ${{ matrix.postgres-version }}
    - run: |
        createdb setup_postgres_test
        psql -d setup_postgres_test -c 'SELECT 1'
